### ISSUE TITLE
Wrong time calculation for some angles

### ISSUE THREAD

**Issue by tmpcache** [forrestguice/SuntimesWidget#875]
[I'm not quite sure what I am reporting here.]

Before version 0.16.6 correct times were being shown for the first three items on the list on the first screenshot.

![Image](https://github.com/user-attachments/assets/fd144a8e-da30-42fe-b269-02b6a7e9359b)

![Image](https://github.com/user-attachments/assets/3177d522-1e5f-499b-bf37-5ebfd9f3f280)

Now, astronomical twilight is given as 'none'. And the two custom angles below it are wrong as well.
Actual sunrise and actual sunset are correct. I don't know about the rest of the items on the list.

**Comment by forrestguice** [comment]
I'll take a closer look and verify the contents of that first screenshot.

The second screenshot looks like an older version of NaturalHour. I see a bug in the twilight periods that should have been fixed in `v0.2.3`. The latest release `v0.3.1` has some cool new features too, but I'd recommend waiting for `v0.3.2` if you are running Android 12+ (and use the widget).

**Comment by tmpcache** [comment]
I updated Natural Hour to `v0.3.2` but this bug is still persisting, which could mean that the bug isn't from Natural Hour.


![Image](https://github.com/user-attachments/assets/4903cda0-ff33-4f23-821a-744c3882b938)


![Image](https://github.com/user-attachments/assets/edcef6ce-44ec-49dd-95ba-ed20690e3f01)

**Comment by tmpcache** [comment]
Did you just say that the sun doesn't reach the 16°-below-the-horizon point at the given time and place? I have another software that gives the times.
For example, SunTimes says that today sun will be 14° below the horizon after sunset at 00:31 but the other app says it's at 23:35.
For 16° below the horizon before sunrise, SunTimes says "none" but the other app says 3:16.

I have to get in touch with the developer of the other app and ask him about the library he uses.

**Comment by verdulo** [comment]
Similar latitude, also the Sun is always higher than -18° above horizon. When you tap on the Sun Position bar, Astronomical twilight is wrongly calculated as 1 d 21 h instead of 3 h.

![Image](https://github.com/user-attachments/assets/419b36b8-623d-49fe-8e51-67bf8a8b7ef1)

**Comment by forrestguice** [comment]
@verdulo Thanks, I think your screenshots show a bug introduced while fixing #878. It should be fixed in the next patch.

@tmpcache I am going to close this issue, but don't let that deter you from opening another (or continuing to add details to this one).
I'm not sure if there is anything actionable for me to do. It is an interesting edge case; the sun approaches some angle but doesn't cross it (that a fraction of a degree in accuracy makes a huge difference).
